model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: FBP_image
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    ckpt_path: pretrained/sr_bsr/model.ckpt
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 160
        attention_resolutions:
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        num_head_channels: 32
        use_checkpoint: True
        
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: pretrained/vqf4_256/checkpoints/last.ckpt
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
          
    cond_stage_config:
      target: ldm.modules.encoders.modules.MTC
      params:
        attn_type: none
        double_z: false
        z_channels: 3
        resolution: 256
        in_channels: 1
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
        
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.ct.CTPistonSRTrainckpt_BP
      params:
        size: 256
        degradation: radon
    validation:
      target: ldm.data.ct.CTPistonSRValidationckpt_BP
      params:
        size: 256
        degradation: radon
        
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        current_mode: train

  trainer:
    benchmark: True

